[project]
name = 'Tokenized-Water-Rights-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.allocation]
path = 'contracts/allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.compliance-contract]
path = 'contracts/compliance-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.rights-holder]
path = 'contracts/rights-holder.clar'
clarity_version = 2
epoch = 2.5

[contracts.transfer]
path = 'contracts/transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-tracking]
path = 'contracts/usage-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
